version: '3'
services:
  frontend:
    build: frontend
    ports:
      - "3000:3000"
      - "3003:3003"
    volumes:
      - ./frontend:/code
      - /code/node_modules
    environment:
      - PORT=3000
  backend:
    build: backend
    depends_on:
      - db
    volumes:
      - ./backend:/code
    ports:
      - "3001:3001"
  db:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
