version: '3'
services:
  frontend:
    build: frontend
    ports:
      - "3000:3000"
      - "3003:3003"
    volumes:
      - ./frontend:/code
      - /code/node_modules
    environment:
      - PORT=3000
