# Generated by Django 2.2.6 on 2019-11-25 01:42

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20191125_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerinformation',
            name='data',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
