# Generated by Django 2.2.6 on 2019-11-25 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20191125_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackerinformation',
            name='id',
        ),
        migrations.AlterField(
            model_name='trackerinformation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tracker_info', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
