# Generated by Django 2.2.6 on 2019-11-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20191125_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackerinformation',
            name='data',
        ),
        migrations.AddField(
            model_name='trackerinformation',
            name='area_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackerinformation',
            name='area_item_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackerinformation',
            name='area_map_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackerinformation',
            name='bricks_destroyed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackerinformation',
            name='creatures_glitched',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackerinformation',
            name='current_health',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackerinformation',
            name='deaths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackerinformation',
            name='difficulty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackerinformation',
            name='overall_item_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackerinformation',
            name='overall_map_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackerinformation',
            name='red_goo_destroyed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
