# Generated by Django 2.2.6 on 2019-11-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_trackerinformation_max_health'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackerinformation',
            name='area_index',
        ),
        migrations.AddField(
            model_name='trackerinformation',
            name='area_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='trackerinformation',
            name='difficulty',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
