# Generated by Django 2.2.6 on 2019-11-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_itemtracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtracker',
            name='address_bomb',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='address_disruptor_1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='address_disruptor_2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='bioflux_1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='bioflux_2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='data_bomb',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='disruptor',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='distortion_field',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='drill',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='drone',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='drone_teleport',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='enhanced_launch',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='firewall',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='flamethrower',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='grapple',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='health_fragments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='health_nodes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='high_jump',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='hypo_atomizer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='intertial_pulse',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='ion_beam',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='kilver',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='lightning_gun',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='multi_disruptor',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='nova',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='orbital_discharge',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='password_tool',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='power_fragments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='power_nodes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='quantum_variegator',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='red_coat',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='reflector',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='reverse_slicer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='shards',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='sudran_key',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='tethered_charge',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='trench_coat',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='turbine_pulse',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtracker',
            name='voranj',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
