# Generated by Django 2.2.6 on 2019-11-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20191128_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtracker',
            name='note_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
