# Generated by Django 2.2.6 on 2019-11-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_itemtracker_fat_beam'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtracker',
            name='heat_seeker',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
