# Generated by Django 2.2.6 on 2019-11-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_auto_20191129_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtracker',
            name='scissorBeam',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
