# Generated by Django 2.2.6 on 2019-11-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_auto_20191129_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtracker',
            name='last_item',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
