# Generated by Django 2.2.8 on 2020-02-29 22:00

from django.db import migrations
from django.contrib.auth.models import User


def forwards_func(apps, schema_editor):
    bad_users = User.objects.filter(username__contains=' ')

    for user in bad_users:
        user.username = user.username.replace(' ', '')
        user.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
