# Generated by Django 2.2.8 on 2020-03-01 04:43

from django.contrib.auth.models import User
from django.db import migrations


def forwards_func(apps, schema_editor):
    CustomUserInformation = apps.get_model('custom_auth', 'CustomUserInformation')
    non_existing = User.objects.filter(custom_info=None)

    for user in non_existing:
        CustomUserInformation.objects.create(user_id=user.id)


def reverse_func(apps, schema_editor):
    CustomUserInformation = apps.get_model('custom_auth', 'CustomUserInformation')
    CustomUserInformation.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_customuserinformation'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
