# Generated by Django 2.2.8 on 2020-03-01 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_create_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserinformation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
