# Generated by Django 2.2.8 on 2020-03-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='category',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
