# Generated by Django 2.2.8 on 2020-03-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
