# Generated by Django 2.2.8 on 2019-12-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
