# Generated by Django 2.2.8 on 2019-12-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_tutorial_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
