name: Lint

'on': [push, pull_request]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Spin up docker containers
      run: docker-compose up --build -d
    - name: Frontend lint
      run: docker-compose exec -T frontend yarn lint
